---
title: Deployment & Data Collection
---

The following sections outline steps in the deployment of PAM hardware and the collection and collating of PAM data. Best practices associated with each step are described, and/or existing resources on the topic are referenced.

This document recognizes that deployment and data collection steps are likely specifically established by entities deploying instruments and collecting data; and in some case these procedures could be proprietary. The following steps outline minimum considerations for ensuring that data being collected by various entities around the region can eventually be collated and analyzed in the future to examine regional-scale questions or issues of interest.

## VI. Definitions for raw, processed, cleaned, and analyzed data

It is expected that PAM data are collected to obtain (either or both) species detection information (e.g., cetacean calls) and ambient or other noise information (e.g., ship detections, construction noise, etc.).

The following data levels (corresponding to the levels described in ADEON's Data Processing Specification document) apply to both types of information and will be used to define what type of data are being referred to in each of the subsequent sections. These levels correspond to a workflow beginning with raw data downloaded directly from the instrument, to processed, cleaned, and/or analyzed data that have been interpreted to develop data products. There are different specifications and data management steps associated with different parts of the workflow. The grouped levels below are a reflection of when similar specifications and data management steps can be applied.

+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Meaning                                                                                                                                                                                                               |
+=========+=======================================================================================================================================================================================================================+
| 0       | Raw, uncalibrated data; compressed, unpacked data                                                                                                                                                                     |
|         |                                                                                                                                                                                                                       |
|         | [Examples:]{.underline} binary files (e.g., BIN, DAT) and SUD compressed files; before the calibration information is applied                                                                                         |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1       | Calibrated time series data                                                                                                                                                                                           |
|         |                                                                                                                                                                                                                       |
|         | [Examples:]{.underline} .wav files (e.g., WAVE, AIFF, FLAC); data processed using software, after calibration is applied; sound pressure on a stationary or moving platform                                           |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2-3     | Processed data from the calibrated data (quantitative and qualitative). Quantitative processing (temporal or spatial)                                                                                                 |
|         |                                                                                                                                                                                                                       |
|         | [Examples:]{.underline} decidecade levels; SEL; depth-integrated data; beamformed data; whale or ship detections/observations; products related to classification of signals; products related to signal localization |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4-5     | Synthesized products related to soundscape models/maps and predictive habitat modeling. Requires additional information (e.g., AIS, source model)                                                                     |
|         |                                                                                                                                                                                                                       |
|         | [Examples:]{.underline} interpolated products; marine mammal density estimation                                                                                                                                       |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

The following flow chart was also adapted from ADEON's Data Processing Specification document to depict the basic sequence of data analysis and reporting suggested for each data level. The rest of this document provides detailed steps and templates for each part of the workflow.

## VII. PAM hardware calibration best practices and minimum specifications

#### (Level 0 data to Level 1 data)

The following steps pertain to pre-deployment best practices.

### Calibration process

For specific examples and details about PAM hardware calibration, refer to ADEON Calibration and Deployment Good Practice Guide, which, while limited to the specific instruments used in the ADEON project, is useful regardless of the system being used.

The following text was taken from NOAA and BOEM Minimum Recommendations for Use of Passive Acoustic Listening Systems in Offshore Wind Energy Development Monitoring and Mitigation Programs (Van Parijs et al., 2021) and refers to specific recommended calibration steps.

> *For all PAM technologies, the hydrophones and related hardware need to be calibrated (every 3 to 5 years) and their performance systematically measured and optimized within frequency bandwidths of interest for the particular activity, species, and environment.*
>
> *All hardware should be tested and optimized for low self-noise, including the mooring system. In addition to calibration, the system should be fully tested to ensure adequate sensitivity in the area where it will be deployed and with the type of signals it would receive. Additional environmental data will need to be collected to allow for adequate system evaluation. If this cannot be done at the project site, the system should be fully tested in a comparable location (i.e., an area exhibiting similar depth, temperature, substrate, current, acoustic propagation, and ambient noise, with relevant sound sources).*
>
> *Ideally, the PAM technology used should have been used for the same purpose in other field efforts and have clear and detailed information available about its previous performance and reliability for PAM purposes. If this is not the case, this information needs to be gathered and provided in publicly available documentation as part of the PAM project.*

### Calibration data and metadata

From NOAA and BOEM Minimum Recommendations for Use of Passive Acoustic Listening Systems in Offshore Wind Energy Development Monitoring and Mitigation Programs (Van Parijs et al., 2021):

> *Calibration data, and relevant settings and sensitivities should be noted for all hardware used in recording/monitoring to ensure consistency among measurements for particular hardware and software \[more detail can be found in Biber et al. (2018) \]. Array synchronization information (where relevant) should also be documented. This information should be permanently associated with the recordings as metadata.*
>
> *At a minimum, the following specifications should be measured and reported on:*
>
> -   *Bandwidth and frequency response (i.e., 10 to 200 kHz)*
>
> -   *System sensitivity (i.e., −207 dB re 1 V/μPa \@ 1 kHz) and dynamic range (dB)*
>
> -   *System self-noise (i.e., the equivalent bandwidth noise pressure level)*
>
> -   *Gain (dB)*
>
> -   *Directional response (i.e., omnidirectional or angular dependent)*
>
> -   *Sample rate (kHz)*
>
> -   *Sample resolution (i.e., 12 Bits)*
>
> -   *Recording schedule (i.e., recording duration/interval)*

## VIII. Best practices for PAM data QA/QC

#### (Level 0 data to Level 1 data)

Once hardware is deployed and data are collected, Quality Assurance/Quality Control steps should be taken to ensure integrity of the data. This step is further split into two separate procedures to include actions that should be taken to properly download and check the data from a PAM device as well as the process to QA/QC the data after being downloaded.

### Before downloading data from the recorder

#### (Level 0 data)

For each PAM deployment there should be an associated deployment information file that contains the recording metadata and calibration information as described above in Section VII. Ensure that these data and the acoustic data files match up and are collated correctly prior to deleting any information off of the actual device. For additional detail on post-retrieval field calibration and data handling best practices, refer to the ADEON Calibration and Deployment Good Practice Guide .

### After downloading data from the recorder

#### (Converting Level 0 data to Level 1 data)

The following procedure was provided by NOAA-NEFSC Passive Acoustic Research Group via Genevieve Davis:

Acoustic Recorders

1.  Create standardized project naming system to separate data from each deployment.

    -   Possible naming structure could be as follows:

        `[RECORDER_ID]_[RECORDING_LOCATION]_[YYYYMMDD of recording start date]_[SITE_NAME]`

    -   It may be helpful to create folders that separate audio files from other files (i.e., log, xml files or raw, uncompressed files)

2.  Spot-check sound files:

    -   Load audio files into sound analysis software (i.e., Raven Pro) and check waveform/spectrograms throughout the deployment: at a minimum, beginning, middle, end

    -   Take a listen to make sure all looks/sounds ok

3.  Verify (and/or record) metadata information on sound files in sound analysis software

    -   Check that date/times line up in sound files with what is recorded in metadata sheets for:

        -   Deployment datetime (gmt)

        -   Recovery datetime (gmt)

        -   Recording start datetime (gmt)

        -   Recording end datetime (gmt)

        -   Usable start datetime (gmt) (when recorder is on and in the water- might be at the beginning of no vessel noise after deployment)

        -   Usable end datetime (gmt) (when recorder is no longer on, in the water- might be the start of recovery vessel noise)

        -   Did the recorder stop recording early?

        -   Did the data get corrupted at any point during the deployment?

4.  Clip beginning and end of deployment to remove invalid data

    -   Recordings when recorder is out of water, or corrupted data

5.  Check data for gaps:

    -   Run a gap detector analysis to make note of any gaps in data

        -   Scripts can be written in Matlab, etc., to do this

6.  Check hydrophone recordings/quality

    -   Was hydrophone working properly the whole time?

    -   Good practice to do for all deployments, all recorders. It can help identify instruments that are failing, or data that is corrupted and cannot be used for any or certain analysis such as soundscape metrics, or identify certain frequencies that were compromised by recorder.

    -   Done by calculating TOL (third octave level) metrics:

        -   Example: using scripts (Matlab, etc.) to subsample recordings to look at 1-2 minutes at start of every sound file

    -   If there are other issues discovered that should be looked at more closely too

Additional Instrument Types (Examples)

-   Active receivers (ex. VEMCO receivers/acoustic releases)

    -   Check to see if there are detections using the chart view in Vue (this is specific for VEMCO receivers) software. Zero detections do not always indicate a problem, but are a good start.

-   Temperature loggers (internal within a recorder, or external instruments)

    -   Plot data output to make sure nothing looks out of the ordinary
