---
title: Planning Steps
---

Planning steps include pre-deployment coordination and communication
best practices that help ensure that any new deployments are responsive
to PAM data gaps and needs in the region (to the extent practicable),
and that individuals or entities responsible for deployments and data
are connected to the existing network of experts and can benefit from
lessons learned and other existing bodies of knowledge.

## I. Engage with the RWSC Marine Mammal Subcommittee

Groups or individuals planning to deploy PAM devices on the Atlantic OCS
for the purposes of detecting cetaceans or characterizing ocean noise
are encouraged to attend RWSC Marine Mammal Subcommittee meetings to
introduce their project, discuss their deployment plan with experts, and
receive input on optimal location and other considerations (visit
https://rwsc.org/events to view the Subcommittee meeting schedule). In
collaboration with the NOAA Passive Acoustics Research Group, the
Subcommittee is maintaining an understanding of PAM devices deployed on
the Atlantic OCS and periodically updating maps that show current
deployments on the Northeast Ocean Data Portal and Mid-Atlantic Ocean
Data Portal (see figure below).

The Portal maps are developed from location and deployment information
shared with NOAA. The following best practices ensure that information
about new and completed deployments is shared with NOAA so that the
Portal maps maintain their accuracy and relevance.

The Portals also contain data products that may assist funders and
researchers in selecting locations for PAM deployment. For example, the
Portals contain data products representing monthly and annual vessel
traffic for several classes of vessels; commercial fishing activity;
offshore wind planning and leasing areas; bathymetry and seafloor
composition information; and monthly density model outputs for 29
cetacean species/guilds. The Subcommittee encourages users to examine
these data to inform PAM deployment site selection.

## II. Codeployment of other sensors

Introducing new PAM instruments and moorings into the environment
presents an opportunity to co-locate other sensors and equipment. For
example, several active and planned PAM deployments include support for
VEMCO receivers or other acoustic telemetry receiver devices. This type
of co-deployment builds the receiver network for studies of other taxa
such as sea turtles and highly migratory fish species, and is strongly
encouraged.

While the location of PAM instruments and moored PAM arrays may not
represent ideal receiver locations needed to address research questions
answered with acoustic telemetry for other taxa, RWSC and its partners
encourage the deployment of multiple sensors per mooring, when
practicable, while research questions and best practices for acoustic
telemetry are under development.

In August 2022, the RWSC Sea Turtle Subcommittee recommended that
acoustic telemetry receivers be included on each new PAM deployment as
the RWSC Marine Mammal Subcommittee considers the design and
implementation of a regional PAM network.

## III. Best Practices to minimize bottom disturbance from underwater mooring systems

Participants in the June 2021 BOEM/NOAA Workshop "Improving Monitoring,
Data Consistency, Archiving, and Access for Improved Regional
Integration of Renewable Energy Science" recommended that best
management practices (BMPs) be developed for any moored or
bottom-mounted equipment used for mitigation, monitoring, and regional
science associated with offshore wind development. These recommended
BMPs are intended to address identified issues but are voluntary and
should be considered supplemental to any other requirements that may be
included under federal or state permits and authorizations. The purpose
of the following BMPs is to provide reasonable conditions to avoid ocean
use conflicts and minimize any potential environmental impacts
associated with scientific devices on or attached to the seafloor.

1.  Review information in ocean data portals and confer with offshore
    wind developers to ensure device deployment areas do not conflict
    with existing or planned cable locations, rights of way, or
    foundation locations.
2.  Properly label all buoys and devices with the responsible operator
    name and contact information.
3.  Avoid known locations of possible unexploded ordnance (UXO).\
4.  Avoid historical or archeological sites.\
5.  Avoid known live bottom (corals, seagrasses, etc.) and sensitive
    hard-bottom features.\
6.  Reduce entanglement or entrapment risk to marine protected species.

[Utilize ocean data portals and coordinate with offshore wind
developers.]{.underline} To the greatest reasonable extent practicable,
deployment locations should be deconflicted prior to deploying any
research or monitoring equipment on the seafloor. Coordination should
occur with offshore leaseholders within lease boundaries and cable
rights of way to ensure current or planned development activities do not
conflict with the deployment or operation of the device.

[Properly label all equipment with the responsible operator name and
contact information.]{.underline} Including identification information
on equipment will assist with identifying the responsible parties for
any equipment that is lost, damaged, or otherwise recovered that is
separated from its moorings.

[Avoid UXO.]{.underline} Avoidance should be the primary strategy to
ensure potential locations of UXO are not interacted with during the
deployment, maintenance, and recovery of scientific devices. Information
for known ordnance areas are available at
https://marinecadastre.gov/data/ and should be checked when identifying
potential device locations and prior to equipment re-deployment. New
potential UXO may also be identified by geophysical and magnetometer
surveys associated with offshore wind data collection.

[Avoid known Historical and archeaological sites.]{.underline} If the
mooring system, anchoring, or equipment (any portion of bottom
disturbance) is to be placed in an area known to be clear or otherwise
was previously surveyed and cleared, then no additional surveys are
required. If the area was previously surveyed and the equipment is
associated with proposed actions under an OCS lease, the lessee should
coordinate with BOEM on any necessary requirements under a lease or
approval conditions of plans.

[Avoid live-bottom features.]{.underline} Mooring systems or equipment
sleds should occur at least 150 m from any known locations of threatened
or endangered coral species. All sensitive live bottom habitats
(eelgrass, cold-water corals, etc.) should be avoided as practicable.
Hard-bottom features including pavement, scarp walls, and
deep/cold-water coral reefs and shallow/mesophotic reefs as defined in
the CMECS Geologic Substrate Classifications) should also be avoided.

[Reduce entanglement and entrapment risk.]{.underline} Mooring or
retrieval systems should have a discountable risk of entangling or
entrapping any marine protected species. Operators should ensure that
any buoys attached to the seafloor use the best available mooring
systems. Buoys, lines (chains, cables, or coated rope systems), swivels,
shackles, and anchor designs should prevent any potential entanglement
of listed species while ensuring the purpose, safety, and integrity of
the structure or device. All mooring lines and ancillary attachment
lines should use one or more of the following measures to reduce
entanglement risk: shortest practicable line length, rubber sleeves,
weak-links, chains, cables, or similar equipment types that prevent
lines from looping, wrapping, or entrapping protected species. Any
equipment should be attached by a line within a rubber sleeve for
rigidity. The length of the line should be as short as necessary to meet
its intended purpose.

## IV. Best Practices to minimize self-noise from underwater mooring systems 
Precautions should be taken to avoid interference of self-noise caused by current flow around the hydrophone and movement of the device and its components. This is especially important in areas with currents greater than 0.1 m/s; to estimate bottom currents for a potential site use the HYCOM model provided by NOAA (https://coastwatch.pfeg.noaa.gov/erddap/griddap/). Flow shields and/or
wraps that protect hydrophones and other device components can also be used to decrease self-noise by disrupting the turbulent boundary layers (ADEON Hardware Specification ). An example of quiet mooring design is described in Baumgartner 2019:

> *We utilized a mature mooring design that allowed both quiet operation
> as well as delivery of digital data from the sea floor to shore
> (Figure 2.1). The DMON was housed in open cell foam and a urethane
> fairing and affixed to a bottom-mounted aluminum frame called the
> multi-function node (MFN), which in turn was attached to the surface
> buoy by stretch hoses. These hoses can stretch to nearly twice their
> relaxed length (Paul & Bocconcelli, 1994), thereby absorbing the
> motion of the buoy in rough wave conditions and keeping the MFN
> acoustically quiet. The hoses also contain helically wound conductors
> that allow power and data to be delivered between the buoy and the
> DMON. The surface buoy contains a platform computer, Iridium and
> global positioning satellite (GPS) antennas, and a 450-Ahr battery
> pack to power all system components. The platform computer receives
> and stores DMON/LFDCS data sent in real-time via the stretch hoses,
> and once every 2 hours, transmits these stored data to shore via an
> Iridium satellite modem (Figure 2.2). The buoy was designed to operate
> at sea for at least one year.*

## V. Navy Awareness of PAM deployments on the Atlantic OCS

The purpose of the following steps is to ensure that the US Navy is
aware of and can provide feedback on the precise location of
bottom-mounted archival passive acoustic monitoring equipment on the
Atlantic OCS. The Navy is requesting that all individuals consider the
following steps prior to deployment. Developers may be subject to
additional requirements under the BOEM issued permits.

1.  Ensure Navy awareness - 45 days prior to deployment Submit Passive
    Acoustic Monitoring (PAM) and/or Distributed Acoustic Sensing (DAS)
    plan to Navy (latitude/longitude, type, make and model of sensor,
    water depth, sample rate, time frame, deployment duration etc.).
    Email Beth Levy: beth.m.levy2.ctr\@us.navy.mil

2.  Navy evaluation and response This step applies to PAM data in all
    locations, not just BOEM lease areas. Provide at least 30 days for
    Navy to evaluate the plan from an operational and acoustic security
    perspective.
    -   [Navy Concurs]{.underline} - The Fleet is able to operate with
        the proposed plan as is. No data screening is needed.

    -   [Navy Concurs with requested conditions]{.underline}

        -   Request Alternative Sensor Location: Navy proposes
            alternative locations that will still allow for original
            monitoring objectives, while maintaining National Security,
            Navy training and readiness.

        -   Request Data Screening: Navy would request the ability to
            screen data from selected sensors and redact potentially
            sensitive data. The screened data set will be returned to
            the owner/collector for their unrestricted use and
            dissemination.
3.  Operator confirms sensor deployment locations
    -   After actual sensor deployment, provide precise metadata to Navy
        within 7 days.
4.  Operator data retrieval
    -   If sensor is not identified for screening, operator can proceed
        with QA/QC and data analysis.

    -   If sensor is identified for requested screening, load data onto
        hard drives, record metadata about location, water depth, etc.

        -   BEFORE an analyst does any QA/QC, follow existing Navy data
            handling and secure storage procedures (a detailed document
            will be provided during step 2 above).

        -   Data will be sent to Navy for screening.

        -   Navy will review and return a redacted data set within 90
            days. o Operator can proceed with analysis on the redacted
            dataset.
5.  Instrument recovery/redeployment Operator will notify Navy if
    instruments are recovered, and/or redeployed in the same location,
    or if settings or location have changed, will restart with step 1
    above.
